### PR TITLE
Updated to support hapi v17

### PR DESCRIPTION
**Pull request by nitinsh99**
Screen Shot 2019-08-05 at 12 28 12 PM

Screen Shot 2019-08-06 at 9 43 34 AM

### CODE REVIEW

**Comment by nitinsh99** [comment]
@danielb2

**Comment by danielb2** [comment]
I was looking at it earlier but didn't have time to act. Thank you for changes :)

**Comment by nitinsh99** [comment]
Thx @danielb2 ..

**Comment by danielb2** [comment]
sorry for the delay here. I'm on vacation and will be back at the end of the month

**Comment by danielb2** [comment]
since hapi is version 18 would you like to take that on ?

**Comment by nitinsh99** [comment]
Hey @danielb2  I tested against `hapi v18` and this plugins seems to be working fine.. Makes sense since signature for 17 and 18 are same.. let me know if this needs to be reflected in readme explicity (that plugin is comptabile with latest hapi version (18.3.2)

Screen Shot 2019-09-01 at 4 16 09 PM

**Pull request merged**
