### PR TITLE
Update to work with hapi 11.x.x-12.x.x. Use lab's built in linting.

### PR DESCRIPTION
**Pull request by briandela**
- Update to work with hapi 11.x.x-12.x.x
- Use lab's built in linting
- Update the code to style to match the lab linting style (which is based on the hapi style)
- Added a `.travis.yml` file to build as node
- Updated the `README.md` with the travis build badge

@danielb2 Let me know if you would like something in the `README.md` mentioning the compatible hapi versions.

### CODE REVIEW

**Comment by briandela** [comment]
Looks like there is no travis.yml file in the repo but travis is configured to try to build it. I've updated my PR with w basic travis.yml which looks like:

```yaml
language: node_js
node_js:
  - 5
  - 4
```

**Comment by danielb2** [comment]
oh this is awesome. Thanks! :)

**Comment by briandela** [comment]
@danielb2 Remind to publish to npm if you feel it's ready :smiley:

**Comment by danielb2** [comment]
I'm ready ;)

**Pull request merged**
